modLoader="javafml"
loaderVersion="[4,)"
license="${license}"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
authors="${authors}"
description='''${modDescription}'''
displayTest="IGNORE_SERVER_VERSION"

[[mixins]]
config="custom_loading_screen.mixins.json"

[[dependencies.${modId}]]
modId="neoforge"
type="required"
versionRange="[${neoforge},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${modId}]]
modId="minecraft"
type="required"
versionRange="${minecraft}"
ordering="NONE"
side="CLIENT"
