modLoader="javafml"
loaderVersion="[4,)"
license="${license}"
issueTrackerURL="${issues}"

[[mods]]
modId="customloadingscreen"
version="${version}"
displayName="${modName}"
authors="${authors}"
description='''${modDescription}'''
displayURL="${homepage}"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.customloadingscreen]]
modId="neoforge"
type="required"
versionRange="[${neoforge},)"
ordering="NONE"
side="CLIENT"

[[dependencies.customloadingscreen]]
modId="minecraft"
type="required"
versionRange="${minecraft}"
ordering="NONE"
side="CLIENT"
